version: '3.9'

services:
  localstack:
    image: localstack/localstack:3
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      DEFAULT_REGION: eu-central-1
      LOCALSTACK_AUTH_TOKEN: ''
    volumes:
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh
      - /var/run/docker.sock:/var/run/docker.sock
