name: Setup Node.js + Yarn 4

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'

    - run: |
        corepack enable
        corepack prepare yarn@4.6.0 --activate
        yarn install --immutable
      shell: bash
